In [0]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

In [2]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [3]:
conv.state_dict()['weight'][0][0]=torch.tensor([[1.0,0,-1.0],[2.0,0,-2.0],[1.0,0.0,-1.0]])
conv.state_dict()['bias'][0] = 0.0
conv.state_dict()

OrderedDict([('weight', tensor([[[[ 1.,  0., -1.],
                        [ 2.,  0., -2.],
                        [ 1.,  0., -1.]]]])), ('bias', tensor([0.]))])

In [4]:
image =torch.zeros(1,1,5,5)
image[0,0,:,2]=1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [5]:
z = conv(image)
z

tensor([[[[-4.,  0.,  4.],
          [-4.,  0.,  4.],
          [-4.,  0.,  4.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [6]:
K = 2
conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=K)
conv1.state_dict()['weight'][0][0]=torch.tensor([[1.0,1.0],[1.0,1.0]])
conv1.state_dict()['bias'][0] = 0.0
conv1.state_dict()
conv1

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1))

In [0]:
M = 4
image1=torch.ones(1,1,M,M)

In [8]:
z1=conv1(image1)
print("z1:", z1)
print("shape:", z1.shape[2:4])

z1: tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
shape: torch.Size([3, 3])


In [0]:
conv3 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=2)
conv3.state_dict()['weight'][0][0]=torch.tensor([[1.0,1.0],[1.0,1.0]])
conv3.state_dict()['bias'][0] = 0.0
conv3.state_dict()

In [11]:
z3 = conv3(image1)

print("z3:", z3)
print("shape:", z3.shape[2:4])

z3: tensor([[[[4., 4.],
          [4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
shape: torch.Size([2, 2])


In [12]:
image1

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [13]:
conv4 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=3)
conv4.state_dict()['weight'][0][0]=torch.tensor([[1.0,1.0],[1.0,1.0]])
conv4.state_dict()['bias'][0] = 0.0
conv4.state_dict()
z4=conv4(image1)
print("z4:", z4)
print("z4:", z4.shape[2:4])

z4: tensor([[[[4.]]]], grad_fn=<MkldnnConvolutionBackward>)
z4: torch.Size([1, 1])


In [14]:
conv5 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=3, padding=1)
conv5.state_dict()['weight'][0][0]=torch.tensor([[1.0,1.0],[1.0,1.0]])
conv5.state_dict()['bias'][0] = 0.0
conv5.state_dict()
z5=conv5(image1)
print("z5:", z5)
print("z5:", z4.shape[2:4])

z5: tensor([[[[1., 2.],
          [2., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
z5: torch.Size([1, 1])


In [16]:
Image = torch.randn((1,1,4,4))
Image

tensor([[[[-0.2223,  0.2630,  1.1942,  0.2277],
          [ 1.3032,  0.7882, -0.0589, -0.4344],
          [ 1.2408,  0.0166, -0.3509,  0.0800],
          [ 0.7425,  0.8135,  0.5510,  0.6168]]]])

In [18]:
conv = nn.Conv2d(in_channels=1, out_channels=1,kernel_size=3)
conv.state_dict()['weight'][0][0]=torch.tensor([[0,0,0],[0,0,0],[0,0.0,0]])
conv.state_dict()['bias'][0]=0.0
conv.state_dict()

z6=conv(Image)
print("z6:", z6)
print("z6:", z6.shape[2:4])



z6: tensor([[[[0., 0.],
          [0., 0.]]]], grad_fn=<MkldnnConvolutionBackward>)
z6: torch.Size([2, 2])
