In [1]:
from torch import nn
import torch
torch.manual_seed(1)

In [0]:
w = torch.tensor([[2.0],[3.0]], requires_grad =True)
b = torch.tensor([[1.0]], requires_grad=True)

In [0]:
def forward(x):
  yhat = torch.mm(x,w) + b
  return yhat

In [4]:
x = torch.tensor([[1.0,2.0]])
yhat = forward(x)
yhat

tensor([[9.]], grad_fn=<AddBackward0>)

In [0]:
X = torch.tensor([[1.0,1.0], [1.0,2.0],[1.0,3.0]])

In [11]:
yhat = forward(X)
yhat

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)

In [0]:
model = nn.Linear(2,1)

In [12]:
yhat = model(x)
print("The result: ",yhat)

The result:  tensor([[-0.3969]], grad_fn=<AddmmBackward>)


In [0]:
class linear_regression(nn.Module):
  def __init__(self, input_size, output_size):
    super(linear_regression, self).__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    yhat = self.linear(x)
    return yhat

In [0]:
model = linear_regression(2,1)

In [15]:
print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


In [16]:
print("The parameters: ", model.state_dict())

The parameters:  OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])), ('linear.bias', tensor([0.4241]))])


In [17]:
yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.5754]], grad_fn=<AddmmBackward>)


In [18]:
yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward>)
