In [0]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
sess = tf.Session()

In [66]:
LSTM_CELL_SIZE = 4  

lstm_cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
state = (tf.zeros([1,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor 'zeros_6:0' shape=(1, 4) dtype=float32>,
 <tf.Tensor 'zeros_6:0' shape=(1, 4) dtype=float32>)

In [67]:
sample_input = tf.constant([[3,2,2,2,2,2,]], dtype=tf.float32)
print(sess.run(sample_input))

[[3. 2. 2. 2. 2. 2.]]


In [69]:
with tf.variable_scope("LSTM_sample"):
     output, state_new = tf.keras.layers.LSTMCell(sample_input, state)
sess.run(tf.global_variables_initializer())
print(sess.run(state_new))

TypeError: ignored

In [0]:
print(sess.run(output))

[[0.00229772 0.11760131 0.18230824 0.27586988]]


In [0]:
sess=tf.Session()

In [0]:
input_dim=6

In [0]:
cells=[]

In [0]:
LSTM_CELL_SIZE_1=4
cell1 = tf.keras.layers.LSTMCell(LSTM_CELL_SIZE_1)
cells.append(cell1)

In [0]:
LSTM_CELL_SIZE_2=5
cell2 = tf.compat.v1.nn.rnn_cell.LSTMCell(LSTM_CELL_SIZE_2)
cells.append(cell2)

In [0]:
stacked_lstm = tf.keras.layers.StackedRNNCells(cells)

In [0]:
data = tf.placeholder(tf.float32, [None, None, input_dim])
output, state = tf.nn.dynamic_rnn(stacked_lstm, data, dtype=tf.float32)

In [77]:
sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]
sample_input

[[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
 [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]

In [78]:
output

<tf.Tensor 'rnn_3/transpose_1:0' shape=(?, ?, 5) dtype=float32>

In [82]:
sess.run(tf.global_variables_initializer())
sess.run(output, feed_dict={data: sample_input})

array([[[-0.00247905,  0.00054164,  0.00744209, -0.00393549,
          0.00357179],
        [-0.00470258, -0.00092245,  0.02701936, -0.02452731,
          0.02895312],
        [-0.0029211 , -0.00120616,  0.0579921 , -0.04703988,
          0.0407723 ]],

       [[-0.00247905,  0.00054164,  0.00744209, -0.00393549,
          0.00357179],
        [ 0.00033214, -0.00217597,  0.04566304, -0.03165321,
          0.02586683],
        [ 0.01040725, -0.0133986 ,  0.07213567, -0.0681283 ,
          0.04722669]]], dtype=float32)