In [0]:
import torch
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
twoD_list = [[11,12,13], [21,22,23], [31,32,33]]
twoD_tensor = torch.tensor(twoD_list)
twoD_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [3]:
print("The dimension of twoD_tensor: ", twoD_tensor.ndimension())
print("The shape of twoD_tensor: ", twoD_tensor.shape)
print("The shape of twoD_tensor: ",twoD_tensor.size())
print("The number of elements in twoD_tensor: ", twoD_tensor.numel())

The dimension of twoD_tensor:  2
The shape of twoD_tensor:  torch.Size([3, 3])
The shape of twoD_tensor:  torch.Size([3, 3])
The number of elements in twoD_tensor:  9


In [4]:
twoD_numpy = twoD_tensor.numpy()
print("Tensor -> Numpy Array:")
print("The numpy array after converting: ", twoD_numpy)
print("Type after converting: ", twoD_numpy.dtype)
print("================================================")

new_twoD_tensor = torch.from_numpy(twoD_numpy)
print("Numpy Array -> Tensor:")
print("The tensor after converting:", new_twoD_tensor)
print("Type after converting: ", new_twoD_tensor.dtype)

Tensor -> Numpy Array:
The numpy array after converting:  [[11 12 13]
 [21 22 23]
 [31 32 33]]
Type after converting:  int64
Numpy Array -> Tensor:
The tensor after converting: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Type after converting:  torch.int64


In [5]:
df = pd.DataFrame({'a':[11,21,31], 'b':[12,22,312]})
print("Pandas Data frame to Numpy: ", df.values)
print("Type Before converting: ", df.values.dtype)
print("----------------------------")
new_tensor = torch.from_numpy(df.values)
print("Tensor AFTER converting: ", new_tensor)
print("Type AFTER converting: ", new_tensor.dtype)

Pandas Data frame to Numpy:  [[ 11  12]
 [ 21  22]
 [ 31 312]]
Type Before converting:  int64
----------------------------
Tensor AFTER converting:  tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
Type AFTER converting:  torch.int64


In [6]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1, 2])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2])

What is the value on 2nd-row 3rd-column?  tensor(23)
What is the value on 2nd-row 3rd-column?  tensor(23)


In [7]:
tensor_example[0,0]

tensor(11)

In [8]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tensor_example[0,0:2]

tensor([11, 12])

In [9]:
tensor_example[0][0:2]

tensor([11, 12])

In [10]:
X = torch.tensor([[1,0],[0,1]])
Y = torch.tensor([[2,1],[1,2]])

X_plus_Y = X + Y
X_plus_Y

tensor([[3, 1],
        [1, 3]])