In [0]:
import torch

In [0]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [0]:
def forward(x):
  yhat = w*x+b
  return yhat

In [5]:
x = torch.tensor([[1,0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[ 1., -1.]], grad_fn=<AddBackward0>)


In [6]:
x = torch.tensor([[1,0],[2,0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 2])


In [7]:
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[ 1., -1.],
        [ 3., -1.]], grad_fn=<AddBackward0>)


In [0]:
x = torch.tensor([[1.0],[2.0],[3.0]])

In [0]:
from torch.nn import Linear

In [10]:
torch.manual_seed(1)

In [17]:
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [13]:
print("Python dictionary: ", lr.state_dict())
print("keys: ", lr.state_dict().keys())
print("values: ", lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [14]:
print("weight:", lr.weight)
print("bias:", lr.bias)

weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [16]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [19]:
x = torch.tensor([[1.0],[2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)


In [21]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
yhat

tensor([[ 0.2755],
        [ 0.0816],
        [-0.1122]], grad_fn=<AddmmBackward>)

In [0]:
from torch import nn

In [0]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super(LR, self).__init__()
    self.linear = nn.Linear(input_size, output_size)
  
  def forward(self, x):
    out = self.linear(x)
    return out

In [24]:
lr = LR(1,1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [25]:
x = torch.tensor([[1.0],[2.0]])
yhat=lr(x)
yhat

tensor([[-0.3417],
        [-1.2832]], grad_fn=<AddmmBackward>)

In [26]:
print("Python dictionary: ", lr.state_dict())
print("keys: ", lr.state_dict().keys())
print("values: ", lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.9414]])), ('linear.bias', tensor([0.5997]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.9414]]), tensor([0.5997])])


In [28]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
yhat

tensor([[-0.3417],
        [-1.2832],
        [-2.2246]], grad_fn=<AddmmBackward>)